# application.yml文件内容==================================================================================
spring:
  application:
    name: service-manager
  profiles:
    active: dev		# 激活的环境文件
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8